spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gp
    username: root
    password: NBVCXZ
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: repairjava.entity
data-path: D:/GP/data
